# Permalinks
permalink:           pretty

# Setup
title:               Tegg Sung
tagline:             Deep learning researcher
url:                 http://tegg89.github.io
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tegg Sung
  url:               https://twitter.com/teggme
  email:             tegg89@gmail.com
  github:            https://github.com/tegg89

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/tegg89

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - kramdown

# Addition
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
